# -*- coding: utf-8 -*-
"""Pandas assement

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GPKXO8vnmUTczeZagCPR2Nb0gqOhZ521
"""

import pandas as pd
import numpy as np

#1
df = pd.read_csv("/finance_economics_dataset.csv", encoding='latin-1')
df

# 1. What is the shape of the dataset?
print(df.shape)

#2. What are the column names and their data types?
print(df.info())

#3. How many unique stock indices are there?
# Count unique stock indices
unique_indices = df['Stock Index'].nunique()

print("Number of unique stock indices:", unique_indices)

# List the actual index names
print("List of Stock Indices:", df['Stock Index'].unique())

# 4. Date range of the dataset
print("Date Range of the Dataset:")
print("Start Date:", df['Date'].min())
print("End Date:", df['Date'].max(), "\n")

# 5. Missing values
print("5️⃣ Missing Values in Each Column:")
print(df.isnull().sum(), "\n")

# 6. Check for negative values in non-negative columns
non_negative_cols = ['Open Price', 'Close Price', 'Daily High', 'Daily Low',
                     'Trading Volume', 'GDP Growth (%)', 'Inflation Rate (%)',
                     'Unemployment Rate (%)', 'Interest Rate (%)',
                     'Consumer Confidence Index', 'Government Debt (Billion USD)',
                     'Corporate Profits (Billion USD)', 'Forex USD/EUR', 'Forex USD/JPY',
                     'Crude Oil Price (USD per Barrel)', 'Gold Price (USD per Ounce)',
                     'Real Estate Index', 'Retail Sales (Billion USD)',
                     'Bankruptcy Rate (%)', 'Mergers & Acquisitions Deals',
                     'Venture Capital Funding (Billion USD)', 'Consumer Spending (Billion USD)']

negative_values = (df[non_negative_cols] < 0).any()
print("Columns with Negative Values:")
print(negative_values[negative_values == True], "\n")

# 7. Summary of GDP Growth (%)
print("Summary of GDP Growth (%):")
print(df['GDP Growth (%)'].describe(), "\n")

# 8. Rows with zero or near-zero trading volume
print("Rows with Zero or Near-Zero Trading Volume:")
print(df[df['Trading Volume'] <= 1], "\n")

# 9. Duplicate rows
print("Duplicate Rows in Dataset:")
print(df[df.duplicated()], "\n")

# 10. Outliers in GDP, Gold, and Oil prices (IQR method)
print("Outliers (IQR Method):")
for col in ['GDP Growth (%)', 'Gold Price (USD per Ounce)', 'Crude Oil Price (USD per Barrel)']:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    outliers = df[(df[col] < (Q1 - 1.5 * IQR)) | (df[col] > (Q3 + 1.5 * IQR))]
    print(f"{col}: {len(outliers)} outliers")
print()

# 11. Summary of Inflation Rate (%)
print(" Summary of Inflation Rate (%):")
print(df['Inflation Rate (%)'].describe(), "\n")

# 12. Average Unemployment Rate
print(" Average Unemployment Rate (%):")
print(df['Unemployment Rate (%)'].mean(), "\n")

# 13. Index with Highest Trading Volume
print(" Stock Index with Highest Trading Volume:")
print(df.groupby('Stock Index')['Trading Volume'].mean().idxmax(), "\n")

# 14. Number of Stock Records from Each Index
print(" Number of Stock Records from Each Index:")
print(df['Stock Index'].value_counts(), "\n")

# 15. Correlation between Inflation and Interest Rate
print("Correlation between Inflation and Interest Rate:")
print(df['Inflation Rate (%)'].corr(df['Interest Rate (%)']), "\n")

# 16. Average Consumer Confidence Index
print("Average Consumer Confidence Index:")
print(df['Consumer Confidence Index'].mean(), "\n")

# 17. Column with Highest Standard Deviation
print("Column with Highest Standard Deviation:")
print(df.std(numeric_only=True).idxmax(), "\n")

# 18. Highest Gold Price Recorded
print(" Highest Gold Price Recorded (USD per Ounce):")
print(df['Gold Price (USD per Ounce)'].max(), "\n")

# 19. Date with Highest Crude Oil Price
print(" Date with Highest Crude Oil Price:")
print(df.loc[df['Crude Oil Price (USD per Barrel)'].idxmax(), 'Date'], "\n")

# 20. Average Corporate Profit
print("Average Corporate Profit (Billion USD):")
print(df['Corporate Profits (Billion USD)'].mean(), "\n")

import matplotlib.pyplot as plt

def show(fig_index=None, save_path=None):
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()
    plt.close()

# 1 Percentage of dataset showing negative GDP growth
plt.figure()
sizes = [(df['GDP Growth (%)'] < 0).sum(), (df['GDP Growth (%)'] >= 0).sum()]
labels = ['Negative GDP', 'Positive GDP']
plt.pie(sizes, labels=labels, autopct='%1.1f%%')
plt.title("Q1: Percentage of Negative GDP Growth")
show()

# 2 Correlation between high inflation and interest rates
plt.figure()
plt.plot(df['Inflation Rate (%)'])
plt.plot(df['Interest Rate (%)'])
plt.xlabel("Index")
plt.ylabel("Value")
plt.title("Q2: Inflation vs Interest Rate (Line Comparison)")
show()

#3.​ Is there a relationship between unemployment and consumer spending
plt.figure()
bubble_size = (df['Unemployment Rate (%)'].fillna(0).values) * 5
plt.scatter(df['Unemployment Rate (%)'], df['Consumer Spending (Billion USD)'], s=bubble_size)
plt.xlabel("Unemployment Rate (%)")
plt.ylabel("Consumer Spending (Billion USD)")
plt.title("Q3: Unemployment vs Consumer Spending (Bubble)")
show()

#4.​ Do higher corporate profits align with higher consumer confidence
plt.figure()
plt.plot(df['Corporate Profits (Billion USD)'])
plt.plot(df['Consumer Confidence Index'])
plt.xlabel("Index")
plt.ylabel("Value")
plt.title("Q4: Corporate Profits vs Consumer Confidence (Line)")
show()

#5.​ What’s the trend of crude oil prices over time
plt.figure()
plt.plot(df['Date'], df['Crude Oil Price (USD per Barrel)'])
plt.xlabel("Date")
plt.ylabel("Crude Oil Price (USD per Barrel)")
plt.title("Q5: Crude Oil Price Trend Over Time")
show()

#6.​ Are gold prices inversely related to stock performance
plt.figure()
plt.scatter(df['Gold Price (USD per Ounce)'], df['Close Price'])
plt.xlabel("Gold Price (USD)")
plt.ylabel("Stock Close Price")
plt.title("Gold Price vs Stock Close Price")
plt.show()

#7.​ Does government debt impact consumer confidence
plt.figure()
plt.plot(df['Government Debt (Billion USD)'])
plt.plot(df['Consumer Confidence Index'])
plt.xlabel("Index")
plt.ylabel("Value")
plt.title("Q7: Government Debt vs Consumer Confidence (Line)")
show()

#8.​ How do mergers & acquisitions (M&A) activity correlate with stock index closing prices
plt.figure()
plt.bar(df.index, df['Mergers & Acquisitions Deals'])
plt.xlabel("Index")
plt.ylabel("Number of Deals")
plt.title("Q8: Mergers & Acquisitions Deals (Bar by record)")
show()

#9.​ Is retail sales growth associated with GDP growth
plt.figure()
bubble_size = (df['Retail Sales (Billion USD)'].fillna(0).values) / 5
plt.scatter(df['Retail Sales (Billion USD)'], df['GDP Growth (%)'], s=bubble_size)
plt.xlabel("Retail Sales (Billion USD)")
plt.ylabel("GDP Growth (%)")
plt.title("Q9: Retail Sales vs GDP Growth (Bubble)")
show()

#10.​Is stock market performance linked to consumer spending
plt.figure()
plt.plot(df['Close Price'])
plt.plot(df['Consumer Spending (Billion USD)'])
plt.xlabel("Index")
plt.ylabel("Value")
plt.title("Q10: Close Price vs Consumer Spending (Line Comparison)")
show()

#11.​Which stock index had the highest average closing price
plt.figure()
avg_close = df.groupby('Stock Index', sort=True)['Close Price'].mean()
plt.bar(avg_close.index, avg_close.values)
plt.xlabel("Stock Index")
plt.ylabel("Average Close Price")
plt.title("Q11: Average Close Price by Stock Index")
plt.xticks(rotation=0)
show()

#12.​What is the relationship between interest rate and unemployment
plt.figure()
plt.plot(df['Interest Rate (%)'])
plt.plot(df['Unemployment Rate (%)'])
plt.xlabel("Index")
plt.ylabel("Value")
plt.title("Q12: Interest Rate vs Unemployment (Line Comparison)")
show()

#13.​Do lower consumer confidence values coincide with higher bankruptcy rates
plt.figure()
plt.plot(df['Bankruptcy Rate (%)'])
plt.xlabel("Index")
plt.ylabel("Bankruptcy Rate (%)")
plt.title("Q13: Bankruptcy Rate Over Time")
show()

#14.​ Which indicator has the highest correlation with stock close price
plt.figure()
numeric = df.select_dtypes(include=[np.number])
corr = numeric.corr()
# use imshow for heatmap (no seaborn)
plt.imshow(corr, aspect='auto', interpolation='nearest')
plt.colorbar(label='Correlation')
plt.title("Q14: Correlation Heatmap")
# label ticks with column names (rotate if many)
plt.xticks(ticks=np.arange(len(corr.columns)), labels=corr.columns, rotation=90)
plt.yticks(ticks=np.arange(len(corr.columns)), labels=corr.columns)
show()

#15.​ Are unemployment rates lower when corporate profits are high
plt.figure()
bubble_size = df['Corporate Profits (Billion USD)'].fillna(0).values / 2
plt.scatter(df['Unemployment Rate (%)'], df['Corporate Profits (Billion USD)'], s=bubble_size)
plt.xlabel("Unemployment Rate (%)")
plt.ylabel("Corporate Profits (Billion USD)")
plt.title("Q15: Unemployment vs Corporate Profits (Bubble)")
show()

df1 = pd.read_csv("/content/Retail Data (2).csv", encoding='latin-1')
df1

"""Sales Retaill  """

# 1 View the structure of the dataset (columns, types, missing values)
print("Columns & Dtypes:\n", df1.dtypes)
print("\nMissing Values:\n", df1.isna().sum())

# 2 Shape (rows, columns)
print("\nQ2 Shape of dataset:", df1.shape)

# 3 Duplicate records
print("\nDuplicate Records:", df1.duplicated().sum())

# 4 Missing/corrupted entries in Ship Date, Order Date, or numeric columns
print("\nMissing in Order Date:", df1['Order Date'].isna().sum())
print("Missing in Ship Date:", df1['Ship Date'].isna().sum())

# Numeric columns check
num_cols = df1.select_dtypes(include=['int64','float64']).columns
print("\nNumeric Columns:", list(num_cols))

#5.Convert Order Date and Ship Date to datetime
df1['Order Date'] = pd.to_datetime(df1['Order Date'], errors='coerce')
df1['Ship Date'] = pd.to_datetime(df1['Ship Date'], errors='coerce')
print("\nConverted Order/Ship Dates to datetime.")

#6.​ Check for future or inconsistent shipping dates
future_dates = df1[df1['Ship Date'] > pd.Timestamp.today()]
inconsistent_dates = df1[df1['Ship Date'] < df1['Order Date']]
print("\nFuture Ship Dates:", len(future_dates))
print("Inconsistent Shipping Dates:", len(inconsistent_dates))

#7.​ Convert price columns to numeric (remove $ and commas)
price_cols = ['Unit Price','Total']
for col in price_cols:
    if col in df1.columns:
        df1[col] = df1[col].astype(str).str.replace('$','').str.replace(',','')
        df1[col] = pd.to_numeric(df1[col], errors='coerce')

print("\nConverted price columns to numeric.")

#8.​ What are the unique values in Customer Type and Order Priority
print("\nCustomer Types:", df1['Customer Type'].unique())
print("Order Priorities:", df1['Order Priority'].unique())

#9 .What are the most common shipping modes
print("\nShipping Mode counts:\n", df1['Ship Mode'].value_counts())

#10.Which cities have the highest number of orders
print("\nTop Cities:\n", df1['City'].value_counts().head(10))

#11.​What’s the range of order quantities and prices
print("Order Quantity Range:", df1['Order Quantity'].min(), "to", df1['Order Quantity'].max())
print("Total Price Range:", df1['Total'].min(), "to", df1['Total'].max())

#12.​Create a new column for shipping duration
df1['Shipping Duration'] = (df1['Ship Date'] - df1['Order Date']).dt.days
print("\nShipping Duration column created.")

#13.​Are there any orders with zero or negative total or quantity
print("\nZero/Negative Quantity:", (df1['Order Quantity'] <= 0).sum())
print("Zero/Negative Total:", (df1['Total'] <= 0).sum())

#14.​Are all discount percentages matching discount dollar amounts
disc_cols = [c for c in df1.columns if 'discount' in c.lower()]
print("Discount Columns:", disc_cols)

# Identify % and $ columns
discount_pct = None
discount_amt = None

for c in disc_cols:
    cl = c.lower()
    if '%' in cl or 'percent' in cl:
        discount_pct = c
    elif '$' in cl or 'amount' in cl:
        discount_amt = c

# Clean & convert
if discount_pct:
    df1[discount_pct] = (
        df1[discount_pct].astype(str)
        .str.replace('%','')
        .str.replace(',','')
    ).astype(float)
    print("\nDiscount % Summary:\n", df1[discount_pct].describe())

if discount_amt:
    df1[discount_amt] = (
        df1[discount_amt].astype(str)
        .str.replace('$','')
        .str.replace(',','')
    ).astype(float)
    print("\nDiscount $ Summary:\n", df1[discount_amt].describe())

if not discount_pct and not discount_amt:
    print("No Discount columns found.")

#15.​ Check for mismatches in total calculation
df1['Expected Total'] = df1['Unit Price'] * df1['Order Quantity']
mismatch = (df1['Expected Total'] != df1['Total']).sum()
print("\nTotal mismatches:", mismatch)

#16.​ Identify top 5 products by order quantity
print("\nTop 5 Products by Quantity:")
print(df1.groupby('Product Name')['Order Quantity'].sum().sort_values(ascending=False).head(5))

#17. Which Account Manager handled the most revenue.
if 'Account Manager' in df1.columns:
    print("\nRevenue by Account Manager:")
    print(df1.groupby('Account Manager')['Total'].sum().sort_values(ascending=False).head(5))
else:
    print("\nAccount Manager column not found.")

# Clean the Shipping Cost column (remove currency symbols if any)
df1['Shipping Cost'] = df1['Shipping Cost'].replace('[\$,]', '', regex=True).astype(float)

# Calculate average shipping cost by mode
avg_shipping_cost = df1.groupby('Ship Mode')['Shipping Cost'].mean().reset_index()

print(avg_shipping_cost)

# Convert Profit column to numeric if needed
df1['Retail Price'] = df1['Retail Price'].replace('[\$,]', '', regex=True).astype(float)

# Calculate profit per product
product_profit = df1.groupby('Product Name')['Retail Price'].sum().reset_index()

# Find the most profitable product
most_profitable = product_profit.sort_values(by='Retail Price', ascending=False).head(1)

print("Most Profitable Product:")
print(most_profitable)

